# Site settings
email: bijlsmalotte@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lotte Bijlsma
description: A Blog about my personal interests
url: ""
twitter_username: bijlsmalotte
default_img: http://res.cloudinary.com/lottebijlsma/image/upload/c_scale,h_800/v1507374566/Blog/Berlin%20Lomography/lotte-urbanspree.jpg

# Profile settings
name: Lotte Bijlsma
profile_img: http://res.cloudinary.com/lottebijlsma/image/upload/c_scale,h_800/v1507374566/Blog/Berlin%20Lomography/lotte-urbanspree.jpg
profile: Hoi, ik ben Lotte. Momenteel een laatstejaars Devine student aan de Howest in Kortrijk. Binnenkort vertrek ik 3 maanden op stage, dit om mijn BA in Devine te finaliseren. Op deze blog breng ik verslag uit. Enjoy!
social:
  github: lottebijlsma

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
