# Site settings
email: bijlsmalotte@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lotte Bijlsma
description: A Blog about my personal interests
url: ""
twitter_username: bijlsmalotte
default_img: http://res.cloudinary.com/lottebijlsma/image/upload/c_scale,h_800/v1507374566/Blog/Berlin%20Lomography/lotte-urbanspree.jpg

# Profile settings
name: Lotte Bijlsma
profile_img: http://res.cloudinary.com/lottebijlsma/image/upload/c_scale,h_800/v1507374566/Blog/Berlin%20Lomography/lotte-urbanspree.jpg
profile: Hi! My name is Lotte. I’m currently a last year Devine (Digital Design & Development) student at Hogeschool West-Vlaanderen in Belgium. This blog is mainly an outlet for daily nonsense, a source to share inspiration and a possibility to share my opinion. But shortly, I will be blogging about my experiences abroad and my design internship at Edenspiekermann! Enjoy!
social:
  github: https://github.com/lottebijlsma/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
