# Site settings
email: bijlsmalotte@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Lotte Bijlsma
description: A Blog about my personal interests
url: ""
twitter_username: bijlsmalotte
default_img: https://lh3.googleusercontent.com/PLwDVJyPcslIVxnKooI-J6PvntN4FiAurJ0WnnVLzOs96E0PKXaKI_osZu3GpZrF9wxXIqJRe0TsZoAdcCE1-P9H6eVI33WNiLpzN-4R1J-9b3bg0JVkAY-Kwi4fjpkn4v88TyRsSkOYDfQZZDiyTaRwYJL1_qPdfVEHUh_w88BaeYOP_XM-E7r753XGDv0qAgi6KEkny87fYgOUNwN6zsHGekRQTlPJeXs0NHJWx4xKpPnhQDpxoTaagT4RO0-J4IcdQ8gYI7jiBZsDdKVjQeQljGmG8R6FKhdalXzGi--4C6KfgzTxrC77-TJWOq5l1-x20qWVZx3-LS0tVkRFE1Ju_XnTlDrNgIdq0INDvXThldqUe55e77BRwHJ0bWXh4J5sT-NVS8rjNtXobTEU5IhpeRyWeDmYGDvkKpRQjGnh-Weo-VxMQkAdZ6DvpSzOiidQSNAlQXGifTSdGJyfsTleXT-nuVkc9W-XOvJps0SPdWkgAoXhIisT3cXvuQ7md4BncGVHcBVragz7uD67yxoEV0s6icKEKdv6LQX0xOkrY7i7awFg_6rUxfehfxU03EEJbzfTzYryJ5XuQJ_VB7xoazvufmXO-eyHwtDBiqsdqkH0ujCraTMxOPEHskMpciCR1J13JyT8qopC9cGXzDYmuBY=w1536-h1018-no

# Profile settings
name: Lotte Bijlsma
profile_img: https://lh3.googleusercontent.com/PLwDVJyPcslIVxnKooI-J6PvntN4FiAurJ0WnnVLzOs96E0PKXaKI_osZu3GpZrF9wxXIqJRe0TsZoAdcCE1-P9H6eVI33WNiLpzN-4R1J-9b3bg0JVkAY-Kwi4fjpkn4v88TyRsSkOYDfQZZDiyTaRwYJL1_qPdfVEHUh_w88BaeYOP_XM-E7r753XGDv0qAgi6KEkny87fYgOUNwN6zsHGekRQTlPJeXs0NHJWx4xKpPnhQDpxoTaagT4RO0-J4IcdQ8gYI7jiBZsDdKVjQeQljGmG8R6FKhdalXzGi--4C6KfgzTxrC77-TJWOq5l1-x20qWVZx3-LS0tVkRFE1Ju_XnTlDrNgIdq0INDvXThldqUe55e77BRwHJ0bWXh4J5sT-NVS8rjNtXobTEU5IhpeRyWeDmYGDvkKpRQjGnh-Weo-VxMQkAdZ6DvpSzOiidQSNAlQXGifTSdGJyfsTleXT-nuVkc9W-XOvJps0SPdWkgAoXhIisT3cXvuQ7md4BncGVHcBVragz7uD67yxoEV0s6icKEKdv6LQX0xOkrY7i7awFg_6rUxfehfxU03EEJbzfTzYryJ5XuQJ_VB7xoazvufmXO-eyHwtDBiqsdqkH0ujCraTMxOPEHskMpciCR1J13JyT8qopC9cGXzDYmuBY=w1536-h1018-no
profile: What's up! My name is Lotte and I'm a design intern at Edenspiekermann Berlin. I love blurting out nonsense and analog photography, that's what probably shows on my blog ;) anyways, hope you have a nice read! See ya!
social:
  github: https://github.com/lottebijlsma/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
